---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: main-app-container
        image: your-main-container-image:your-tag
        ports:
        - containerPort: 80
      - name: sidecar-container
        image: your-sidecar-container-image:your-tag
        # Add other container configuration as needed
