---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-app-cronjob
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: my-app
        spec:
          containers:
          - name: my-app-container
            image: your-container-image:your-tag
            # Add other container configuration as needed
          restartPolicy: OnFailure
